sudo: required
services:
    - docker
    
 before_install:
    - docker build -t aviv/react-test -f ./client/Dockerfile.dev ./client/Dockerfile

script:    
  - docker run -e CI=true aviv/react-test npm test
  
after_success:
    - docker build -t aviv/multi-client ./client
    - docker build -t aviv/multi-nginx ./nginx
    - docker build -t aviv/multi-server ./server
    - docker build -t aviv/multi-worker ./worker