language: generic 
sudo: required
services:
    - docker
    
 before_install:
    - docker build -t aviv/react-test -f ./client/Dockerfile.dev ./client/Dockerfile

script:    
  - docker run -e CI=true aviv/react-test npm test
  
after_success:
    - docker build -t aviv/multi-client ./client
    - docker build -t aviv/multi-nginx ./nginx
    - docker build -t aviv/multi-server ./server
    - docker build -t aviv/multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKE_PASSWORD" | docker login -u "$DOCER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push aviv/multi-client
    - docker push aviv/multi-nginx
    - docker push aviv/multi-server
    - docker push aviv/multi-worker